name: mediasfu_sdk
description: "MediaSFU SDK for Flutter provides powerful streaming capabilities for creating high-performance cross-platform applications."
version: 0.0.6
homepage: https://www.mediasfu.com
repository: https://github.com/MediaSFU/MediaSFU_SDK_Flutter


environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0
  url_launcher: ^6.2.5
  clipboard: ^0.1.3
  flutter_colorpicker: ^1.0.3
  mediasfu_mediasoup_client: ^0.0.3
  http: ^1.2.1
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  flutter_webrtc: ^0.11.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/whatsapp.jpg
  fonts:
    - family: FontAwesome
      fonts:
        - asset: fonts/FontAwesome.ttf
        