name: mediasfu_sdk
description: "MediaSFU SDK for Flutter provides powerful streaming capabilities for creating high-performance cross-platform applications."
version: 2.1.9
homepage: https://www.mediasfu.com
repository: https://github.com/MediaSFU/MediaSFU_SDK_Flutter


environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^3.0.2
  url_launcher: ^6.2.5
  clipboard: ^2.0.2
  flutter_colorpicker: ^1.0.3
  mediasfu_mediasoup_client: ^0.0.8
  http: ^1.2.1
  intl: ^0.20.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  flutter_webrtc: ^1.0.0
  audioplayers: ^6.1.0
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dartdoc: ^8.0.7


flutter:
  uses-material-design: true
  assets:
  - assets/whatsapp.jpg
  fonts:
    - family: FontAwesome
      fonts:
        - asset: fonts/FontAwesome.ttf
        