import 'package:flutter/material.dart';
import 'package:mediasfu_mediasoup_client/mediasfu_mediasoup_client.dart';
import '../../types/types.dart';

/// This map contains the initial values for the state in the application.
/// It includes various properties related to the meeting room, participants, recording, audio/video settings, and more.
final Map<String, dynamic> initialValuesState = {
  // Socket and device information
  'socket': null,
  'roomData': ResponseJoinRoom(),
  'device': null,
  'apiKey': '',
  'apiUserName': '',
  'apiToken': '',
  'link': '',

  // Room Details
  'roomName': '',
  'member': '',
  'adminPasscode': '',
  'islevel': '0',
  'coHost': 'No coHost',
  'coHostResponsibility': [
    CoHostResponsibility(name: 'participants', value: false, dedicated: false),
    CoHostResponsibility(name: 'media', value: false, dedicated: false),
    CoHostResponsibility(name: 'waiting', value: false, dedicated: false),
    CoHostResponsibility(name: 'chat', value: false, dedicated: false),
  ],
  'youAreCoHost': false,
  'youAreHost': false,
  'confirmedToRecord': false,
  'meetingDisplayType': 'media',
  'meetingVideoOptimized': false,
  'eventType': EventType.webinar,
  'participants': <Participant>[],
  'filteredParticipants': <Participant>[],
  'participantsCounter': 0,
  'participantsFilter': '',
  'consumeSockets': <ConsumeSocket>[],
  'rtpCapabilities': null,
  'roomRecvIPs': <String>[],
  'meetingRoomParams': null,
  'itemPageLimit': 4,
  'audioOnlyRoom': false,
  'addForBasic': false,
  'screenPageLimit': 4,
  'shareScreenStarted': false,
  'shared': false,
  'targetOrientation': 'landscape',
  'targetResolution': 'sd',
  'targetResolutionHost': 'sd',
  'vidCons': VidCons(
    width: DimensionConstraints(ideal: 640),
    height: DimensionConstraints(ideal: 480),
  ),
  'frameRate': 5,
  'hParams': null,
  'vParams': null,
  'screenParams': null,
  'aParams': null,

  // Recording Details
  'recordingAudioPausesLimit': 0,
  'recordingAudioPausesCount': 0,
  'recordingAudioSupport': false,
  'recordingAudioPeopleLimit': 0,
  'recordingAudioParticipantsTimeLimit': 0,
  'recordingVideoPausesCount': 0,
  'recordingVideoPausesLimit': 0,
  'recordingVideoSupport': false,
  'recordingVideoPeopleLimit': 0,
  'recordingVideoParticipantsTimeLimit': 0,
  'recordingAllParticipantsSupport': false,
  'recordingVideoParticipantsSupport': false,
  'recordingAllParticipantsFullRoomSupport': false,
  'recordingVideoParticipantsFullRoomSupport': false,
  'recordingPreferredOrientation': 'landscape',
  'recordingSupportForOtherOrientation': false,
  'recordingMultiFormatsSupport': false,

  // User Recording Parameters
  'userRecordingParams': UserRecordingParams(
    mainSpecs: MainSpecs(
      mediaOptions: 'video',
      audioOptions: 'all',
      videoOptions: 'all',
      videoType: 'fullDisplay',
      videoOptimized: false,
      recordingDisplayType: 'media',
      addHLS: false,
    ),
    dispSpecs: DispSpecs(
      nameTags: true,
      backgroundColor: '#000000',
      nameTagsColor: '#ffffff',
      orientationVideo: 'portrait',
    ),
  ),

  // Recording States
  'canRecord': false,
  'startReport': false,
  'endReport': false,
  'recordTimerInterval': null,
  'recordStartTime': 0,
  'recordElapsedTime': 0,
  'isTimerRunning': false,
  'canPauseResume': false,
  'recordChangeSeconds': 15000,
  'pauseLimit': 0,
  'pauseRecordCount': 0,
  'canLaunchRecord': true,
  'stopLaunchRecord': false,
  'participantsAll': <Participant>[],

  // General Settings
  'firstAll': false,
  'updateMainWindow': false,
  'firstRound': false,
  'landScaped': false,
  'lockScreen': false,
  'screenId': '',
  'allVideoStreams': <Stream>[],
  'newLimitedStreams': <Stream>[],
  'newLimitedStreamsIDs': <String>[],
  'activeSounds': <String>[],
  'screenShareIDStream': '',
  'screenShareNameStream': '',
  'adminIDStream': '',
  'adminNameStream': '',
  'youYouStream': [],
  'youYouStreamIDs': <String>[],
  'localStream': null,
  'recordStarted': false,
  'recordResumed': false,
  'recordPaused': false,
  'recordStopped': false,
  'adminRestrictSetting': false,
  'videoRequestState': 'none',
  'videoRequestTime': null,
  'localStreamVideo': null,
  'userDefaultVideoInputDevice': '',
  'currentFacingMode': 'user',
  'prevFacingMode': 'user',
  'defVideoID': '',
  'allowed': false,
  'dispActiveNames': <String>[],
  'pDispActiveNames': <String>[],
  'activeNames': <String>[],
  'prevActiveNames': <String>[],
  'pActiveNames': <String>[],
  'membersReceived': false,
  'deferScreenReceived': false,
  'hostFirstSwitch': false,
  'micAction': false,
  'screenAction': false,
  'chatAction': false,
  'audioRequestState': 'none',
  'screenRequestState': 'none',
  'chatRequestState': 'none',
  'audioRequestTime': null,
  'screenRequestTime': null,
  'chatRequestTime': null,
  'updateRequestIntervalSeconds': 240,
  'oldSoundIds': <String>[],
  'hostLabel': 'Host',
  'mainScreenFilled': false,
  'localStreamScreen': null,
  'screenAlreadyOn': false,
  'chatAlreadyOn': false,
  'redirectURL': '',
  'oldAllStreams': <Stream>[],
  'adminVidID': '',
  'streamNames': <Stream>[],
  'nonAlVideoStreams': <Stream>[],
  'sortAudioLoudness': false,
  'audioDecibels': <AudioDecibels>[],
  'mixedAlVideoStreams': <Stream>[],
  'nonAlVideoStreamsMuted': <Stream>[],
  'paginatedStreams': <List<Stream>>[],
  'localStreamAudio': null,
  'defAudioID': '',
  'userDefaultAudioInputDevice': '',
  'userDefaultAudioOutputDevice': '',
  'prevAudioInputDevice': '',
  'prevVideoInputDevice': '',
  'audioPaused': false,
  'mainScreenPerson': '',
  'adminOnMainScreen': false,
  'screenStates': [
    ScreenState(
      mainScreenPerson: null,
      mainScreenProducerId: null,
      mainScreenFilled: false,
      adminOnMainScreen: false,
    ),
  ],
  'prevScreenStates': [
    ScreenState(
      mainScreenPerson: null,
      mainScreenProducerId: null,
      mainScreenFilled: false,
      adminOnMainScreen: false,
    ),
  ],
  'updateDateState': null,
  'lastUpdate': null,
  'nForReadjustRecord': 0,
  'fixedPageLimit': 4,
  'removeAltGrid': false,
  'nForReadjust': 0,
  'reorderInterval': 30000,
  'fastReorderInterval': 10000,
  'lastReorderTime': 0,
  'audStreamNames': <Stream>[],
  'currentUserPage': 0,
  'isWideScreen': false,
  'isMediumScreen': false,
  'isSmallScreen': false,
  'addGrid': false,
  'addAltGrid': false,
  'gridRows': 0,
  'gridCols': 0,
  'altGridRows': 0,
  'altGridCols': 0,
  'numberPages': 0,
  'currentStreams': <Stream>[],
  'showMiniView': false,
  'nStream': null,
  'deferReceive': false,
  'allAudioStreams': <Stream>[],
  'remoteScreenStream': <Stream>[],
  'screenProducer': null,
  'gotAllVids': false,
  'paginationHeightWidth': 40.0,
  'paginationDirection': 'horizontal',
  'gridSizes': GridSizes(
    gridWidth: 0,
    gridHeight: 0,
    altGridWidth: 0,
    altGridHeight: 0,
  ),
  'screenForceFullDisplay': false,
  'mainGridStream': <Widget>[],
  'otherGridStreams': [<Widget>[], <Widget>[]],
  'audioOnlyStreams': <Widget>[],
  'videoInputs': <MediaDeviceInfo>[],
  'audioInputs': <MediaDeviceInfo>[],
  'meetingProgressTime': '00:00:00',
  'meetingElapsedTime': 0,
  'refParticipants': <Participant>[],
  'messages': <Message>[],
  'startDirectMessage': false,
  'directMessageDetails': null,
  'showMessagesBadge': false,
  'audioSetting': 'allow',
  'videoSetting': 'allow',
  'screenshareSetting': 'allow',
  'chatSetting': 'allow',
  'autoWave': true,
  'forceFullDisplay': true,
  'prevForceFullDisplay': false,
  'prevMeetingDisplayType': 'video',
  'waitingRoomFilter': '',
  'waitingRoomList': <WaitingRoomParticipant>[],
  'waitingRoomCounter': 0,
  'filteredWaitingRoomList': <WaitingRoomParticipant>[],
  'requestFilter': '',
  'requestList': <Request>[],
  'requestCounter': 0,
  'filteredRequestList': <Request>[],
  'transportCreated': false,
  'transportCreatedVideo': false,
  'transportCreatedAudio': false,
  'transportCreatedScreen': false,
  'producerTransport': null,
  'videoProducer': null,
  'params': null,
  'videoParams': null,
  'audioParams': null,
  'audioProducer': null,
  'consumerTransports': <TransportType>[],
  'consumingTransports': <String>[],
  'polls': <Poll>[],
  'poll': null,
  'isPollModalVisible': false,
  'breakoutRooms': <List<BreakoutParticipant>>[],
  'currentRoomIndex': 0,
  'canStartBreakout': false,
  'breakOutRoomStarted': false,
  'breakOutRoomEnded': false,
  'hostNewRoom': -1,
  'limitedBreakRoom': <BreakoutParticipant>[],
  'mainRoomsLength': 0,
  'memberRoom': -1,
  'isBreakoutRoomsModalVisible': false,
  'isPortrait': true,
  'customImage': null,
  'selectedImage': null,
  'segmentVideo': null,
  'selfieSegmentation': null,
  'pauseSegmentation': false,
  'processedStream': null,
  'keepBackground': false,
  'backgroundHasChanged': false,
  'virtualStream': null,
  'mainCanvas': null,
  'prevKeepBackground': false,
  'appliedBackground': false,
  'isBackgroundModalVisible': false,
  'autoClickBackground': false,
  'whiteboardUsers': <WhiteboardUser>[],
  'currentWhiteboardIndex': null,
  'canStartWhiteboard': false,
  'whiteboardStarted': false,
  'whiteboardEnded': false,
  'whiteboardLimit': 0,
  'isWhiteboardModalVisible': false,
  'isConfigureWhiteboardModalVisible': false,
  'shapes': <dynamic>[],
  'useImageBackground': true,
  'redoStack': <dynamic>[],
  'undoStack': <String>[],
  'canvasStream': null,
  'canvasWhiteboard': null,
  'canvasScreenboard': null,
  'processedScreenStream': null,
  'annotateScreenStream': false,
  'mainScreenCanvas': null,
  'isScreenboardModalVisible': false,
  'alertVisible': false,
  'alertMessage': '',
  'alertType': 'info',
  'alertDuration': 3000,
  'progressTimerVisible': true,
  'progressTimerValue': 0,
  'isMenuModalVisible': false,
  'isRecordingModalVisible': false,
  'isSettingsModalVisible': false,
  'isRequestsModalVisible': false,
  'isWaitingModalVisible': false,
  'isCoHostModalVisible': false,
  'isMediaSettingsModalVisible': false,
  'isDisplaySettingsModalVisible': false,
  'totalReqWait': 0,
  'isParticipantsModalVisible': false,
  'isMessagesModalVisible': false,
  'isConfirmExitModalVisible': false,
  'isConfirmHereModalVisible': false,
  'isShareEventModalVisible': false,
  'isLoadingModalVisible': false,
  'recordingMediaOptions': 'video',
  'recordingAudioOptions': 'all',
  'recordingVideoOptions': 'all',
  'recordingVideoType': 'fullDisplay',
  'recordingVideoOptimized': false,
  'recordingDisplayType': 'media',
  'recordingAddHLS': true,
  'recordingNameTags': true,
  'recordingBackgroundColor': '#83c0e9',
  'recordingNameTagsColor': '#ffffff',
  'recordingAddText': false,
  'recordingCustomText': 'Add Text',
  'recordingCustomTextPosition': 'top',
  'recordingCustomTextColor': '#ffffff',
  'recordingOrientationVideo': 'landscape',
  'clearedToResume': true,
  'clearedToRecord': true,
  'recordState': 'green',
  'showRecordButtons': false,
  'recordingProgressTime': '00:00:00',
  'audioSwitching': false,
  'videoSwitching': false,
  'videoAlreadyOn': false,
  'audioAlreadyOn': false,
  'hasCameraPermission': false,
  'hasAudioPermission': false,
  'componentSizes': ComponentSizes(
    mainHeight: 0,
    otherHeight: 0,
    mainWidth: 0,
    otherWidth: 0,
  ),
};
